server:
  port: 8034
spring:
  application:
    name: eureka-server-2
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8033/eureka/
    register-with-eureka: true
    fetch-registry: true