server:
  port: 8102
spring:
  application:
    name: eureka-producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka
  instance:
    statusPageUrlPath: http://${eureka.instance.hostname}:${server.port}/actuator/info
    healthCheckUrlPath: http://${eureka.instance.hostname}:${server.port}/actuator/health
    hostname: localhost