server:
  port: 8051
spring:
  application:
    name: eureka-producer
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0   # 采样比例设置 1.0 全部获取  0->1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8052/eureka
  instance:
    statusPageUrlPath: http://${eureka.instance.hostname}:${server.port}/actuator/info
    healthCheckUrlPath: http://${eureka.instance.hostname}:${server.port}/actuator/health
    hostname: localhost
logging:
  level:
    Root: debug