server:
  port: 8091
spring:
  application:
    name: stream-rabbitmq
  rabbitmq:
    username: admin
    password: admin
  cloud:
    stream:
      bindings:
        input:
          group: test
          destination: test