server:
  port: 8035
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8033/eureka,http://localhost:8034/eureka
  instance:
    statusPageUrlPath: http://${eureka.instance.hostname}:${server.port}/actuator/info
    healthCheckUrlPath: http://${eureka.instance.hostname}:${server.port}/actuator/health
    hostname: localhost