server:
  port: 8094
spring:
  application:
    name: stream-kafka-input
  cloud:
    stream:
      bindings:
        input:
          group: test
          destination: test
  kafka:
    bootstrap-servers: localhost:9092
    client-id: input