server:
  port: 8056
spring:
  application:
    name: sleuth-zipkin-rabbitmq
  rabbitmq:
    username: admin
    password: admin
    host: localhost
  zipkin:
#    base-url: http://localhost:9411
    sender:
      type: rabbit
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
#logging:
#  level:
#    Root: debug