server:
  port: 8071
spring:
  application:
    name: gateway-server-eureka
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
      routes:
        - id: producer
          uri: lb://eureka-producer
          predicates:
            - name: Path
              args:
                - pattern: /**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8073/eureka