server:
  port: 8070
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://www.lovem.wang
          predicates:
            - args:
              - pattern: /**
              name: Path
