server:
  port: 8070
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
#            allowedMethods:
#            - GET
      routes:
        - id: test
          uri: http://www.lovem.wang
          filters:
            - StripPrefix=1
          predicates:

            - Path=/foo/**
#            - args:
#              - pattern: /blog/**
#              name: Path
logging:
  level:
    root: debug
