server:
  port: 8040
spring:
  application:
    name: zuul-geteway-url
zuul:
  ignored-patterns: '*'
  routes:
    blog:
      path: /blog/**
      url: http://www.baidu.com
    git:
      path: /git/**
      url: http://www.lovem.wang
logging:
  level:
    root: debug
